---
title: "Model Analysis"
output: html_notebook
---

## Setup

```{r}
library(lubridate)
library(tidyverse)
library(rstanarm)
library(bayesplot)
```

```{r}
load("full_df.rda")
full_df_ts2
```


## Helpers

Data sampler

```{r}
# df:     dataframe to sample from
# years:  vector of years to include
# months: vector of months to include
# dhour:  which hours to pick (hour %% dhour == 0)
data_sampler <- function(df, years, months, ddays, dhour) {
  sample <- df %>% filter(
                    year(datetime) %in% years &
                    month(datetime) %in% months &
                    day(datetime) %% ddays == 0 &
                    hour(datetime) %% dhour == 0
                  )
  return(sample)
}
```

Error calculator
```{r}
model_error <- function(post, test_sample) {
  DRAWS <- 1000
  post_pred <- as_tibble(posterior_predict(post, test_sample, draws = DRAWS))
  num_data_points <- ncol(post_pred) / 17
  
  predicted = c()
  for (i in 1:num_data_points) {
    predicted <- append(predicted, rowMeans(exp(post_pred[,((i-1)*17+1):(i*17)])))
  }
  
  real <- rep(test_sample[seq(1, nrow(test_sample), by = 17), 2]$energy, each = DRAWS)
  
  errors <- tibble(predicted = predicted, real = real) %>% mutate(error = predicted - real)
  return(errors)
}
```


## Data plotting

```{r}
ggplot(
    data = data_sampler(full_df, c(2019), c(12), 3, 22),
    aes(x = w10, y = energy)
  ) +
  geom_point()
```




## w10, log target, ts=0

```{r}
load("post_w10_log.rda")
post_w10_log
```

**Error**

Calculate
```{r}
error_w10_log <- model_error(
                            post_w10_log,
                            data_sampler(full_df, c(2019), c(12), 3, 22))
```



Some stats
```{r}
summary(error_w10_log)
```


Plot
```{r}
mcmc_areas(error_w10_log,
           pars = c("error"),
           prob = 0.5,
           prob_outer = 0.999) +
  xlim(-2000, 2000) +
  scale_x_continuous(breaks = c(-1000, -750, -500, -250, -100, 0, 100, 250, 500, 750)) +
  xlab("Error [MWh]")
```


__________________________________________________________________________________________________________


## w10, log target, ts=2

```{r}
load("post_w10_log_ts2.rda")
post_w10_log_ts2
```


**Error**

Calculate
```{r}
error_w10_log_ts2 <- model_error(
                            post_w10_log_ts2,
                            data_sampler(full_df_ts2, c(2019), c(12), 3, 22))
```



Some stats
```{r}
summary(error_w10_log_ts2)
```


Plot
```{r}
mcmc_areas(error_w10_log_ts2,
           pars = c("error"),
           prob = 0.5,
           prob_outer = 0.999) +
  xlim(-2000, 2000) +
  scale_x_continuous(breaks = c(-1000, -750, -500, -250, -100, 0, 100, 250, 500, 750)) +
  xlab("Error [MWh]")
```



__________________________________________________________________________________________________________


## w10, log target, ts=6

```{r}
load("post_w10_log_ts6.rda")
post_w10_log_ts6
```

**Error**

Calculate
```{r}
error_w10_log_ts6 <- model_error(
                            post_w10_log_ts6,
                            data_sampler(full_df_ts6, c(2019), c(12), 3, 22))
```



Some stats
```{r}
summary(error_w10_log_ts6)
```


Plot
```{r}
mcmc_areas(error_w10_log_ts6,
           pars = c("error"),
           prob = 0.5,
           prob_outer = 0.999) +
  xlim(-2000, 2000) +
  scale_x_continuous(breaks = c(-1000, -750, -500, -250, -100, 0, 100, 250, 500, 750)) +
  xlab("Error [MWh]")
```





__________________________________________________________________________________________________________


## w10, log target, ts=24

```{r}
load("post_w10_log_ts24.rda")
post_w10_log_ts24
```

**Error**

Calculate
```{r}
error_w10_log_ts24 <- model_error(
                            post_w10_log_ts24,
                            data_sampler(full_df_ts24, c(2019), c(12), 3, 22))
```



Some stats
```{r}
summary(error_w10_log_ts24)
```


Plot
```{r}
mcmc_areas(error_w10_log_ts24,
           pars = c("error"),
           prob = 0.5,
           prob_outer = 0.999) +
  xlim(-2000, 2000) +
  scale_x_continuous(breaks = c(-1000, -750, -500, -250, -100, 0, 100, 250, 500, 750)) +
  xlab("Error [MWh]")
```


## w10, w100, log target, ts=0

```{r}
load("post_w10_w100_log.rda")
post_w10_w100_log
```

**Error**

Calculate
```{r}
error_w10_w100_log <- model_error(
                            post_w10_w100_log,
                            data_sampler(full_df, c(2019), c(12), 3, 22))
```



Some stats
```{r}
summary(error_w10_w100_log)
```

Plot
```{r}
mcmc_areas(error_w10_w100_log,
           pars = c("error"),
           prob = 0.5,
           prob_outer = 0.999) +
  xlim(-2000, 2000) +
  scale_x_continuous(breaks = c(-1000, -750, -500, -250, -100, 0, 100, 250, 500, 750)) +
  xlab("Error [MWh]")
```


_________________________________________________________________________________________________________________________________________



## w10, w100, log target, ts=2

```{r}
load("post_w10_w100_log_ts2.rda")
post_w10_w100_log_ts2
```

**Error**

Calculate
```{r}
error_w10_w100_log_ts2 <- model_error(
                            post_w10_w100_log_ts2,
                            data_sampler(full_df, c(2019), c(12), 3, 22))
```



Some stats
```{r}
summary(error_w10_w100_log_ts2)
```


Plot
```{r}
mcmc_areas(error_w10_w100_log_ts2,
           pars = c("error"),
           prob = 0.5,
           prob_outer = 0.999) +
  xlim(-2000, 2000) +
  scale_x_continuous(breaks = c(-1000, -750, -500, -250, -100, 0, 100, 250, 500, 750)) +
  xlab("Error [MWh]")
```


_____________________________________________________________________________________________________________
