---
title: "ERA Interim data"
output: html_notebook
---

# Aggregate models

```{r}
library(arrow)
library(lubridate)
library(dplyr)
library(rstanarm)
library(ggplot2)
library(bayesplot)
```


```{r}
# rstanarm options
options(mc.cores = parallel::detectCores())
# Bayesplot
theme_set(bayesplot::theme_default())
```

## Start stuff

Parameters

```{r}
months = 6
```

Load and preprocess predictors

```{r}
predictors <- arrow::read_feather("data/predictors/wind_region_mean_2018-01to06.feather")
N = nrow(predictors)
# The datetimes are in UTC.02 because of Feather I guess? They are actually just UTC
head(predictors)
```

Load and preprocess target

```{r}
# Load
energy <- read.csv("data/energy/events_2018.csv")

# Drop unnecessary columns
energy <- subset(energy, select=-c(Lopetusaika.UTC, Alkuaika.UTC.02.00, Lopetusaika.UTC.02.00))

# simplify remaining column names
colnames(energy)[1] = "datetime"
colnames(energy)[2] = "energy"

# Drop timesteps not included in predictors (include month 1 and hours 00, 06, 12, 18)
target <- energy %>% filter(month(.$datetime) <= months) %>% filter(hour(.$datetime) %% 6 == 0)

target
```
## Full aggregate linear model

More preprocessing
```{r}
predictors_fa <- predictors %>%
                              transmute(
                                U10 = rowMeans(.[,1:17]),
                                V10 = rowMeans(.[,18:34]),
                                W10 = rowMeans(.[,34:51]),
                                datetime)
 
predictors_fa
```

```{r}
data_fa <- predictors_fa
data_fa["energy"] <- target$energy
head(data_fa)
```

With W component
```{r}
post_fa_1 <- stan_glm(energy ~ W10,
              data = data_fa,
              family = gaussian(link = "identity"))
```

```{r}
summary(post_fa_1)
```

```{r}
base <- ggplot(data_fa, aes(x = W10, y = energy)) +
         geom_point(size=1)
base + geom_abline(intercept = coef(post_fa_1)[1], slope = coef(post_fa_1)[2])
```

```{r}
draws_fa_1 <- as.data.frame(post_fa_1)
colnames(draws_fa_1) <- c("a", "b", "sigma")
head(draws_fa_1)
```
```{r}
base +
  geom_abline(data = draws_fa_1, aes(intercept = a, slope = b),
              color = "skyblue", size = 0.2, alpha = 0.25) +
  geom_abline(intercept = coef(post_fa_1)[1], slope = coef(post_fa_1)[2],
              color = "skyblue4", size = 1)
```

Separate U and V component
```{r}
post_fa_2 <- stan_glmer(log(energy) ~ W10,
              data = data_fa,
              family = gaussian(link = "identity")) # lognormal
```

```{r}
data_ra <- predictors[,34:51]
data_ra["energy"] <- target$energy
data_ra
```


```{r}
post_ra_1 <- stan_glm(energy ~ w10_0 + w10_1 + w10_2 + w10_3 + w10_4 + w10_5 + w10_6 + w10_7 + w10_8 + w10_9 + w10_10 + w10_11 + w10_12 + w10_13 + w10_14 + w10_15 + w10_16,
              data = data_ra,
              family = gaussian(link = "identity"))
```

```{r}
post_ra_1
```
 








